//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class dil {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal dil() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebUI.Resources.dil", typeof(dil).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AKSESUARLAR.
        /// </summary>
        public static string Aksesuarlar {
            get {
                return ResourceManager.GetString("Aksesuarlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alisveris Klavuzu.
        /// </summary>
        public static string AlisverisKlavuz {
            get {
                return ResourceManager.GetString("AlisverisKlavuz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANA SAYFA.
        /// </summary>
        public static string AnaSayfa {
            get {
                return ResourceManager.GetString("AnaSayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ara.
        /// </summary>
        public static string Ara {
            get {
                return ResourceManager.GetString("Ara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banka Bismilleri.
        /// </summary>
        public static string BankaBismilleri {
            get {
                return ResourceManager.GetString("BankaBismilleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çağrı Merkezi.
        /// </summary>
        public static string CagriMerkezi {
            get {
                return ResourceManager.GetString("CagriMerkezi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destek.
        /// </summary>
        public static string Destek {
            get {
                return ResourceManager.GetString("Destek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EN SON ÇIKAN PC OYUNLARI.
        /// </summary>
        public static string EnSonPC {
            get {
                return ResourceManager.GetString("EnSonPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EN SON ÇIKAN PS4 OYUNLARI.
        /// </summary>
        public static string EnSonPS4 {
            get {
                return ResourceManager.GetString("EnSonPS4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EN SON ÇIKAN XBOX ONE OYUNLARI.
        /// </summary>
        public static string EnSonXbox1 {
            get {
                return ResourceManager.GetString("EnSonXbox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Ticaret.
        /// </summary>
        public static string eticaret {
            get {
                return ResourceManager.GetString("eticaret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        public static string GirisYap {
            get {
                return ResourceManager.GetString("GirisYap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gizlilik Taahhüdü.
        /// </summary>
        public static string GizlilikTaahhudu {
            get {
                return ResourceManager.GetString("GizlilikTaahhudu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkımızda.
        /// </summary>
        public static string Hakkimizda {
            get {
                return ResourceManager.GetString("Hakkimizda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim.
        /// </summary>
        public static string Iletisim {
            get {
                return ResourceManager.GetString("Iletisim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İnsan Kaynakları.
        /// </summary>
        public static string InsanKaynaklari {
            get {
                return ResourceManager.GetString("InsanKaynaklari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kargo Takibi.
        /// </summary>
        public static string KargoTakip {
            get {
                return ResourceManager.GetString("KargoTakip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Ol.
        /// </summary>
        public static string KayitOl {
            get {
                return ResourceManager.GetString("KayitOl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlayStation 4 Konsol.
        /// </summary>
        public static string KonsolPs4 {
            get {
                return ResourceManager.GetString("KonsolPs4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xbox One Konsol.
        /// </summary>
        public static string KonsolXbox1 {
            get {
                return ResourceManager.GetString("KonsolXbox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KUPONLAR.
        /// </summary>
        public static string Kuponlar {
            get {
                return ResourceManager.GetString("Kuponlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurumsal.
        /// </summary>
        public static string Kurumsal {
            get {
                return ResourceManager.GetString("Kurumsal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurumsal Satış.
        /// </summary>
        public static string KurumsalSatis {
            get {
                return ResourceManager.GetString("KurumsalSatis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markalar.
        /// </summary>
        public static string Markalar {
            get {
                return ResourceManager.GetString("Markalar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC Oyunları.
        /// </summary>
        public static string OyunPC {
            get {
                return ResourceManager.GetString("OyunPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlayStation 4 Oyunları.
        /// </summary>
        public static string OyunPs4 {
            get {
                return ResourceManager.GetString("OyunPs4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xbox One Oyunları.
        /// </summary>
        public static string OyunXbox1 {
            get {
                return ResourceManager.GetString("OyunXbox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola.
        /// </summary>
        public static string Parola {
            get {
                return ResourceManager.GetString("Parola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parolayı Onayla.
        /// </summary>
        public static string ParolaOnay {
            get {
                return ResourceManager.GetString("ParolaOnay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POPULER PC OYUNLARI.
        /// </summary>
        public static string PopPC {
            get {
                return ResourceManager.GetString("PopPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POPULER PS4 OYUNLARI.
        /// </summary>
        public static string PopPS4 {
            get {
                return ResourceManager.GetString("PopPS4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POPULER XBOX ONE OYUNLARI.
        /// </summary>
        public static string PopXbox1 {
            get {
                return ResourceManager.GetString("PopXbox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sosyal Ağlar ile Bağlan.
        /// </summary>
        public static string SosyalAg {
            get {
                return ResourceManager.GetString("SosyalAg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm PC Oyunları.
        /// </summary>
        public static string TumPCOyun {
            get {
                return ResourceManager.GetString("TumPCOyun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm PS4 Oyunları.
        /// </summary>
        public static string TumPS4Oyun {
            get {
                return ResourceManager.GetString("TumPS4Oyun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm XBOX ONE Oyunları.
        /// </summary>
        public static string TumXbox1Oyun {
            get {
                return ResourceManager.GetString("TumXbox1Oyun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Adı.
        /// </summary>
        public static string UrunAdi {
            get {
                return ResourceManager.GetString("UrunAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün İade Şartları.
        /// </summary>
        public static string UrunIade {
            get {
                return ResourceManager.GetString("UrunIade", resourceCulture);
            }
        }
    }
}
